spring:
  profiles:
    include:
      - docker
      - dev

cloud:
  aws:
    credentials:
      accessKey: ${aws-s3-access-key}
      secretKey: ${aws-s3-secret-key}
    s3:
      bucket: ${aws-s3-bucket-name}
    region:
      static: ap-northeast-2
    stack:
      auto: false